---
repos:

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: [--target-version=py36]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args:
          - --py36-plus

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: .bumpversion.cfg
      - id: end-of-file-fixer
        exclude: tests/data/
      - id: check-json
        files: \.(json)$
      - id: check-yaml
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: pretty-format-json
        args:
          - --autofix

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies: [
          # flake8-blind-except, FIXME
          flake8-builtins,
          flake8-rst-docstrings,
          flake8-logging-format,
        ]
        args: [
          # black/flake8 interactions
          # https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#minimal-configuration
          "--max-line-length=88",
          "--extend-ignore=E203, E701",
          "--rst-roles=class,func,ref,module,const",
          "--exclude=docs/conf.py",
        ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        exclude: tests/|setup.py|docs/conf.py

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        args: [
          --disallow-untyped-defs,
          --ignore-missing-imports,
        ]
        exclude: tests/|setup.py|docs/conf.py

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
